import OpenAI from 'openai'

// Tek bir LLM çağrısının bekleyebileceği azami süre. Bu analiz 4 ayrı
// alanda 220+ kelimelik, çok paragraflı derin metin üretiyor — 15sn çoğu
// zaman yetmiyordu ve "Request timed out" hatasına sebep oluyordu.
export const PROVIDER_TIMEOUT_MS = 50_000
// Bir worker koşusunda LLM aşaması için ayrılan bütçe (görsel üretime de yer bırakır).
export const REQUEST_DEADLINE_MS = 55_000

const SUPPORTED_LANGS = {
  tr: 'Turkish',
  en: 'English',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  pt: 'Portuguese',
  ru: 'Russian',
  ja: 'Japanese'
}

const SYSTEM_PROMPT = `You are the premium deep dream analysis engine for Lunosfer.

You are not a generic wellness assistant and not a shallow motivational writer.
You produce psychologically rich, symbolically precise, emotionally intelligent, and narratively coherent deep dream analyses rooted primarily in Jungian interpretation, while also using broader psychodynamic reasoning when useful.

NON-NEGOTIABLE RULES:
1. Return VALID JSON only.
2. Never use markdown fences.
3. Follow the exact JSON schema.
4. Detect the dream's original language and write the full analysis in that language.
5. The ONLY field that must remain in English is "visual_prompt_en".
6. Do not produce generic encouragement, vague spirituality, repetitive filler, or bland self-help clichés.
7. Interpret symbols in relation to the actual dream scenes, emotional transitions, conflicts, and actions.
8. Do not force cosmic or mystical symbolism onto ordinary dreams.
9. Preserve ambiguity where appropriate; do not overclaim certainty.
10. Write like a perceptive analyst, not like autogenerated content.

DEPTH REQUIREMENTS:
- "summary" must be concise but meaningful.
- "motiv" must identify the main psychic movement, urge, or tension.
- "sentiment" must describe the emotional atmosphere with nuance.
- "shadow_focus", "core_conflict", "individuation_path", and "symbolic_reading" must each contain at least TWO long, substantial paragraphs.
- These sections must not merely paraphrase each other.
- Each deep section has a different task:
  • shadow_focus = disowned tendencies, defended affects, forbidden wishes, shame-bound material, aggression, envy, dependency, exposure, moral tension
  • core_conflict = central intrapsychic struggle, relational contradiction, identity split, control dilemma, concealment vs revelation, safety vs vitality
  • individuation_path = what psychic rebalancing, integration, mourning, differentiation, courage, or self-confrontation is being invited
  • symbolic_reading = close reading of settings, actions, transitions, objects, authority figures, thresholds, pursuit, concealment, repetition, and dream logic
- "persona_profile" should infer cautiously from the dream, not diagnose.
- "archetypes" should include only truly relevant archetypal patterns.
- "reflection_questions" must be thoughtful, concrete, and emotionally penetrating — exactly 3.
- "symbols" and "emotions" must be grounded in the dream rather than filled with generic labels.

SHORT DREAM RULE:
If the dream is short, do NOT become shallow.
Use the emotional tone, setting, behavioral pattern, and symbolic tension to produce a dense analysis.
A short dream does not justify a weak interpretation.

VISUAL PROMPT RULE:
"visual_prompt_en" must describe the single most vivid scene from the dream in clear English.
It must remain faithful to the literal dream content.
Avoid generic fantasy landscapes unless explicitly present in the dream.

STYLE:
- Elegant, deep, precise, and readable.
- Compassionate but unsentimental.
- Insightful but not dogmatic.
- Symbolically literate without becoming obscure.
- No clichés.
- No filler.
- No empty positivity.

Return premium-quality JSON.`

function buildShape() {
  return {
    title: '',
    summary: '',
    motiv: '',
    sentiment: '',
    visual_prompt_en: '',
    archetypes: [],
    shadow_focus: '',
    core_conflict: '',
    individuation_path: '',
    symbolic_reading: '',
    reflection_questions: ['', '', ''],
    persona_profile: {
      name: '',
      tagline: '',
      public_self: '',
      hidden_self: '',
      strengths: [],
      core_fears: [],
      emotional_needs: []
    },
    symbols: [{ symbol: '', meaning: '', intensity: 0 }],
    emotions: [{ emotion: '', score: 0 }]
  }
}

function collapseSpaces(str) {
  let result = str
  while (result.indexOf('  ') !== -1) {
    result = result.split('  ').join(' ')
  }
  return result
}

export function cleanText(text = '') {
  const NEWLINE = String.fromCharCode(10)
  const CARRIAGE = String.fromCharCode(13)
  const TAB = String.fromCharCode(9)

  const replaced = String(text)
    .split(NEWLINE).join(' ')
    .split(CARRIAGE).join(' ')
    .split(TAB).join(' ')

  return collapseSpaces(replaced).trim()
}

function textWordCount(text = '') {
  return cleanText(text).split(' ').filter(Boolean).length
}

function countParagraphs(text = '') {
  const NEWLINE = String.fromCharCode(10)
  const lines = String(text).split(NEWLINE)

  let paragraphs = 0
  let inParagraph = false

  for (const line of lines) {
    if (cleanText(line).length > 0) {
      if (!inParagraph) {
        paragraphs++
        inParagraph = true
      }
    } else {
      inParagraph = false
    }
  }

  return paragraphs
}

function looksEnglishHeavy(text = '') {
  const padded = ' ' + cleanText(text).toLowerCase() + ' '
  const englishMarkers = [
    ' the ', ' and ', ' with ', ' dream ', ' shadow ', ' conflict ',
    ' self ', ' fear ', ' mother ', ' father ', ' hidden ', ' need '
  ]
  return englishMarkers.some((marker) => padded.indexOf(marker) !== -1)
}

function hasAnyWord(text, words) {
  const padded = ' ' + text + ' '
  return words.some((w) => padded.indexOf(' ' + w + ' ') !== -1)
}

export function detectDreamLanguage(dreamText, requestedLang) {
  const text = cleanText(dreamText).toLowerCase()

  if (/[çğıöşü]/.test(text) || hasAnyWord(text, ['ben', 'rüyamda', 'rüyada', 'kapı', 'evde', 'annem', 'babam', 'kaçıyordum', 'gördüm', 'yakalanıyordum'])) return 'tr'
  if (/[а-яё]/.test(text)) return 'ru'
  if (/[ぁ-んァ-ン一-龯]/.test(text)) return 'ja'
  if (hasAnyWord(text, ['el', 'la', 'los', 'las', 'soñé', 'sueño', 'casa', 'miedo', 'puerta'])) return 'es'
  if (hasAnyWord(text, ['le', 'la', 'les', 'rêve', 'maison', 'peur', 'porte', 'dans'])) return 'fr'
  if (hasAnyWord(text, ['der', 'die', 'das', 'ich', 'traum', 'haus', 'angst', 'tür'])) return 'de'
  if (hasAnyWord(text, ['o', 'a', 'os', 'as', 'sonho', 'casa', 'medo', 'porta', 'estava'])) return 'pt'
  if (hasAnyWord(text, ['the', 'dream', 'house', 'fear', 'mother', 'running', 'door', 'caught'])) return 'en'

  return requestedLang && SUPPORTED_LANGS[requestedLang] ? requestedLang : 'en'
}

export function buildPrompt({ dreamContent, detectedLang, pastContext }) {
  const targetLanguage = SUPPORTED_LANGS[detectedLang] || 'English'

  return `
${SYSTEM_PROMPT}

DETECTED DREAM LANGUAGE:
${targetLanguage}

CRITICAL LANGUAGE CONSTRAINT:
- Every field except "visual_prompt_en" must be written in ${targetLanguage}.
- "visual_prompt_en" must remain in English only.

PREVIOUS DREAM PATTERN CONTEXT:
${pastContext}

DREAM TO ANALYZE:
${dreamContent}

REQUIRED JSON SHAPE:
${JSON.stringify(buildShape())}
  `.trim()
}

function buildRepairPrompt({ originalPrompt, previousOutput, issues }) {
  return `
Your previous answer was not acceptable.

You must repair it and return a stronger new JSON response.

FAILURES TO FIX:
${issues.join(', ')}

ORIGINAL INSTRUCTIONS:
${originalPrompt}

PREVIOUS BAD OUTPUT:
${previousOutput}

REPAIR RULES:
- Return only valid JSON.
- Strengthen all weak sections substantially.
- If deep sections were too short, expand them with genuinely new insight.
- If the language was wrong, rewrite all non-English-required fields in the correct detected dream language.
- If symbolism was generic, ground it in the dream's concrete scenes and emotional logic.
- If paragraphs were insufficient, make at least two substantial paragraphs in each required deep field.
- Keep "visual_prompt_en" in English only.
  `.trim()
}

function buildJsonRepairPrompt(rawOutput) {
  return `
Convert the following malformed output into valid JSON ONLY.
Do not summarize it.
Do not explain it.
Do not wrap in markdown.
Preserve as much semantic content as possible while fixing structure.

MALFORMED OUTPUT:
${rawOutput}

Return valid JSON only.
  `.trim()
}

function safeJsonParse(raw) {
  if (!raw) throw new Error('empty_model_response')

  const cleaned = String(raw)
    .replace(/```json/g, '')
    .replace(/```/g, '')
    .trim()

  const firstBrace = cleaned.indexOf('{')
  const lastBrace = cleaned.lastIndexOf('}')

  if (firstBrace === -1 || lastBrace === -1) {
    throw new Error('json_braces_not_found')
  }

  return JSON.parse(cleaned.slice(firstBrace, lastBrace + 1))
}

function coerceAnalysisShape(data) {
  const shape = buildShape()

  const merged = {
    ...shape,
    ...(data || {}),
    persona_profile: {
      ...shape.persona_profile,
      ...(data?.persona_profile || {})
    }
  }

  merged.title = String(merged.title || '')
  merged.summary = String(merged.summary || '')
  merged.motiv = String(merged.motiv || '')
  merged.sentiment = String(merged.sentiment || '')
  merged.visual_prompt_en = String(merged.visual_prompt_en || '')
  merged.shadow_focus = String(merged.shadow_focus || '')
  merged.core_conflict = String(merged.core_conflict || '')
  merged.individuation_path = String(merged.individuation_path || '')
  merged.symbolic_reading = String(merged.symbolic_reading || '')

  merged.archetypes = Array.isArray(merged.archetypes) ? merged.archetypes.filter(Boolean).slice(0, 8) : []

  merged.reflection_questions = Array.isArray(merged.reflection_questions)
    ? merged.reflection_questions.filter(Boolean).slice(0, 3)
    : ['', '', '']

  while (merged.reflection_questions.length < 3) merged.reflection_questions.push('')

  merged.symbols = Array.isArray(merged.symbols)
    ? merged.symbols.filter(Boolean).slice(0, 8).map((s) => ({
        symbol: String(s?.symbol || ''),
        meaning: String(s?.meaning || ''),
        intensity: Math.max(0, Math.min(100, Number(s?.intensity) || 0))
      }))
    : []

  merged.emotions = Array.isArray(merged.emotions)
    ? merged.emotions.filter(Boolean).slice(0, 8).map((e) => ({
        emotion: String(e?.emotion || ''),
        score: Math.max(0, Math.min(100, Number(e?.score) || 0))
      }))
    : []

  merged.persona_profile.strengths = Array.isArray(merged.persona_profile.strengths)
    ? merged.persona_profile.strengths.filter(Boolean).slice(0, 8)
    : []

  merged.persona_profile.core_fears = Array.isArray(merged.persona_profile.core_fears)
    ? merged.persona_profile.core_fears.filter(Boolean).slice(0, 8)
    : []

  merged.persona_profile.emotional_needs = Array.isArray(merged.persona_profile.emotional_needs)
    ? merged.persona_profile.emotional_needs.filter(Boolean).slice(0, 8)
    : []

  return merged
}

function validateAnalysisQuality(analysis, detectedLang) {
  const issues = []

  if (!analysis?.title || textWordCount(analysis.title) < 2) issues.push('weak_title')
  if (!analysis?.summary || textWordCount(analysis.summary) < 35) issues.push('weak_summary')
  if (!analysis?.motiv || textWordCount(analysis.motiv) < 12) issues.push('weak_motiv')
  if (!analysis?.sentiment || textWordCount(analysis.sentiment) < 10) issues.push('weak_sentiment')
  if (!analysis?.visual_prompt_en || textWordCount(analysis.visual_prompt_en) < 22) issues.push('weak_visual_prompt')

  const deepFields = ['shadow_focus', 'core_conflict', 'individuation_path', 'symbolic_reading']

  for (const field of deepFields) {
    const value = analysis?.[field] || ''
    if (textWordCount(value) < 220) issues.push(`too_short_${field}`)
    if (countParagraphs(value) < 2) issues.push(`not_enough_paragraphs_${field}`)
  }

  if (!Array.isArray(analysis?.reflection_questions) || analysis.reflection_questions.filter(Boolean).length < 3) {
    issues.push('missing_reflection_questions')
  }

  if (!Array.isArray(analysis?.symbols) || analysis.symbols.length < 2) {
    issues.push('missing_symbols')
  }

  if (!Array.isArray(analysis?.emotions) || analysis.emotions.length < 2) {
    issues.push('missing_emotions')
  }

  if (!Array.isArray(analysis?.archetypes) || analysis.archetypes.length < 2) {
    issues.push('missing_archetypes')
  }

  if (detectedLang !== 'en') {
    const nonEnglishFields = [
      analysis?.summary,
      analysis?.motiv,
      analysis?.sentiment,
      analysis?.shadow_focus,
      analysis?.core_conflict,
      analysis?.individuation_path,
      analysis?.symbolic_reading
    ].filter(Boolean)

    const englishHeavyCount = nonEnglishFields.filter(looksEnglishHeavy).length
    if (englishHeavyCount >= 3) issues.push('wrong_analysis_language')
  }

  return {
    pass: issues.length === 0,
    issues
  }
}

async function callOpenAICompatible({ baseURL, apiKey, model, prompt, providerName, extraHeaders = {} }) {
  const client = new OpenAI({ apiKey, baseURL, timeout: PROVIDER_TIMEOUT_MS, maxRetries: 0 })

  const response = await client.chat.completions.create({
    model,
    temperature: 0.9,
    response_format: { type: 'json_object' },
    messages: [
      { role: 'system', content: 'Return only valid JSON. Respect all depth, structure, and language rules.' },
      { role: 'user', content: prompt }
    ]
  }, { headers: extraHeaders })

  const raw = response?.choices?.[0]?.message?.content
  if (!raw) throw new Error(`${providerName}_empty_response`)

  return { raw, parsed: coerceAnalysisShape(safeJsonParse(raw)) }
}

async function repairMalformedJson({ baseURL, apiKey, model, providerName, rawOutput, extraHeaders = {} }) {
  const client = new OpenAI({ apiKey, baseURL, timeout: PROVIDER_TIMEOUT_MS, maxRetries: 0 })

  const response = await client.chat.completions.create({
    model,
    temperature: 0.2,
    response_format: { type: 'json_object' },
    messages: [
      { role: 'system', content: 'Repair malformed structured outputs into valid JSON only.' },
      { role: 'user', content: buildJsonRepairPrompt(rawOutput) }
    ]
  }, { headers: extraHeaders })

  const raw = response?.choices?.[0]?.message?.content
  if (!raw) throw new Error(`${providerName}_json_repair_empty_response`)

  return { raw, parsed: coerceAnalysisShape(safeJsonParse(raw)) }
}

async function repromptForQuality({ baseURL, apiKey, model, providerName, originalPrompt, previousOutput, issues, extraHeaders = {} }) {
  const client = new OpenAI({ apiKey, baseURL, timeout: PROVIDER_TIMEOUT_MS, maxRetries: 0 })

  const response = await client.chat.completions.create({
    model,
    temperature: 0.95,
    response_format: { type: 'json_object' },
    messages: [
      { role: 'system', content: 'Return only repaired, high-quality JSON that strictly satisfies the schema.' },
      { role: 'user', content: buildRepairPrompt({ originalPrompt, previousOutput, issues }) }
    ]
  }, { headers: extraHeaders })

  const raw = response?.choices?.[0]?.message?.content
  if (!raw) throw new Error(`${providerName}_repair_empty_response`)

  return { raw, parsed: coerceAnalysisShape(safeJsonParse(raw)) }
}

function buildOpenAIProvider(prompt) {
  const openaiKey = process.env.OPENAI_API_KEY || process.env.OPENAI_KEY
  if (!openaiKey) return null

  return {
    name: 'openai',
    baseURL: 'https://api.openai.com/v1',
    apiKey: openaiKey,
    model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
    extraHeaders: {},
    prompt
  }
}

function getProviders(prompt) {
  const providers = []

  // Normal jung analizinde (pages/api/analyze-dream.js) kullanılan aynı OpenAI
  // anahtarı — en güvenilir sağlayıcı olduğu için zincirin başında deneniyor.
  // Boş yanıt dönerse callOpenAICompatible hata fırlatır ve döngü otomatik
  // olarak sıradaki sağlayıcıya geçer.
  const openaiProvider = buildOpenAIProvider(prompt)
  if (openaiProvider) providers.push(openaiProvider)

  if (process.env.OPENROUTER_API_KEY) {
    providers.push({
      name: 'openrouter_primary',
      baseURL: 'https://openrouter.ai/api/v1',
      apiKey: process.env.OPENROUTER_API_KEY,
      model: process.env.OPENROUTER_MODEL || 'openrouter/auto',
      extraHeaders: {
        'HTTP-Referer': process.env.NEXT_PUBLIC_APP_URL || 'https://dreamap.app',
        'X-Title': 'Dreamap Deep Analysis'
      },
      prompt
    })
  }

  if (process.env.GROQ_API_KEY) {
    providers.push({
      name: 'groq',
      baseURL: 'https://api.groq.com/openai/v1',
      apiKey: process.env.GROQ_API_KEY,
      model: 'llama-3.3-70b-versatile',
      extraHeaders: {},
      prompt
    })
  }

  if (process.env.CEREBRAS_API_KEY) {
    providers.push({
      name: 'cerebras',
      baseURL: 'https://api.cerebras.ai/v1',
      apiKey: process.env.CEREBRAS_API_KEY,
      model: 'llama-3.3-70b',
      extraHeaders: {},
      prompt
    })
  }

  if (process.env.HUGGINGFACE_API_KEY) {
    providers.push({
      name: 'huggingface',
      baseURL: 'https://router.huggingface.co/v1',
      apiKey: process.env.HUGGINGFACE_API_KEY,
      model: 'deepseek-ai/DeepSeek-V3-0324',
      extraHeaders: {},
      prompt
    })
  }

  if (process.env.GITHUB_MODELS_TOKEN) {
    providers.push({
      name: 'github_models',
      baseURL: 'https://models.github.ai/inference',
      apiKey: process.env.GITHUB_MODELS_TOKEN,
      model: 'openai/gpt-4.1-mini',
      extraHeaders: {},
      prompt
    })
  }

  if (process.env.NVIDIA_NIM_API_KEY) {
    providers.push({
      name: 'nvidia_nim',
      baseURL: 'https://integrate.api.nvidia.com/v1',
      apiKey: process.env.NVIDIA_NIM_API_KEY,
      model: 'meta/llama-3.1-8b-instruct',
      extraHeaders: {},
      prompt
    })
  }

  return providers
}

async function tryProvider(provider, detectedLang, deadlineAt) {
  let firstRaw = null

  try {
    const first = await callOpenAICompatible({
      baseURL: provider.baseURL,
      apiKey: provider.apiKey,
      model: provider.model,
      prompt: provider.prompt,
      providerName: provider.name,
      extraHeaders: provider.extraHeaders
    })

    firstRaw = first.raw
    const firstQuality = validateAnalysisQuality(first.parsed, detectedLang)

    // NOT: Önceden burada kalite kontrolden geçmeyen sonuçlar için AYRI bir
    // "repromptForQuality" LLM çağrısı daha yapılıyordu. Bu, tek bir analizi
    // pratikte 2 ayrı OpenAI isteğine (2x süre) çeviriyordu ve senkron
    // istekte 60sn sınırına takılmaya sebep oluyordu. Artık ilk cevap kalite
    // kontrolden geçmese bile (coerceAnalysisShape zaten şekli garanti ediyor)
    // olduğu gibi kabul ediliyor; sadece loglanıyor.
    if (!firstQuality.pass) {
      console.warn(`process-deep-analysis: quality issues accepted as-is for speed (${provider.name}):`, firstQuality.issues.join(', '))
    }

    return { ok: true, analysis: first.parsed, provider: provider.name }
  } catch (error) {
    if (firstRaw) {
      try {
        const jsonRepaired = await repairMalformedJson({
          baseURL: provider.baseURL,
          apiKey: provider.apiKey,
          model: provider.model,
          providerName: provider.name,
          rawOutput: firstRaw,
          extraHeaders: provider.extraHeaders
        })

        return { ok: true, analysis: jsonRepaired.parsed, provider: provider.name }
      } catch (repairError) {
        return {
          ok: false,
          provider: provider.name,
          reason: repairError.message || error.message || 'provider_failed'
        }
      }
    }

    return {
      ok: false,
      provider: provider.name,
      reason: error.message || 'provider_failed'
    }
  }
}

// PLAN A: senkron istek döngüsü içinde SADECE OpenAI'ı dener (kuyruk/cron'a hiç
// girmeden). generate-deep-analysis.js bunu çağırır; başarısız/boş/zaman aşımı
// olursa çağıran taraf PLAN B'ye (mevcut kuyruk + cron worker akışı) düşer.
export async function generateWithOpenAIOnly(prompt, detectedLang, deadlineAt) {
  const provider = buildOpenAIProvider(prompt)
  if (!provider) throw new Error('openai_not_configured')

  const result = await tryProvider(provider, detectedLang, deadlineAt)
  if (!result.ok) {
    const err = new Error(result.reason || 'openai_failed')
    err.issues = result.issues
    throw err
  }

  return { analysis: result.analysis, provider: result.provider }
}

export async function generateBestAnalysis(prompt, detectedLang, deadlineAt) {
  const providers = getProviders(prompt)
  if (!providers.length) throw new Error('no_llm_provider_configured')

  const failures = []

  for (const provider of providers) {
    if (Date.now() > deadlineAt) {
      failures.push({ provider: provider.name, reason: 'skipped_time_budget_exhausted' })
      break
    }

    const result = await tryProvider(provider, detectedLang, deadlineAt)

    if (result.ok) {
      return { analysis: result.analysis, provider: result.provider }
    }

    failures.push({
      provider: result.provider,
      reason: result.reason,
      issues: result.issues || []
    })
  }

  const err = new Error('all_providers_failed')
  err.failures = failures
  throw err
}

export async function generateImageIfPossible(visualPrompt) {
  if (!process.env.REPLICATE_API_TOKEN || !visualPrompt) return null

  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), 20_000)

  try {
    const rep = await fetch('https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.REPLICATE_API_TOKEN}`,
        'Content-Type': 'application/json',
        Prefer: 'wait=15'
      },
      body: JSON.stringify({
        input: { prompt: visualPrompt, aspect_ratio: '1:1' }
      }),
      signal: controller.signal
    })

    const data = await rep.json()
    return data?.output?.[0] || null
  } catch (e) {
    console.error('Flux Failed', e)
    return null
  } finally {
    clearTimeout(timeoutId)
  }
}
