// English dream guides under /dream-meanings/[slug]. Same shape as
// dreamGuides.js. English Instagram posts link here (they used to land on the
// Turkish /ruya-tabirleri pages). `tr` = matching Turkish slug, for hreflang.

export const GUIDES_EN_UPDATED = '2026-10-06'

const Q = 'Questions to ask yourself'
const S = 'Common scenarios'
const K = 'Short answer'

export const DREAM_GUIDES_EN = [
  {
    slug: 'snake-dream-meaning',
    tr: 'ruyada-yilan-gormek',
    title: 'Snake Dream Meaning: What It Means to Dream of Snakes (Jung)',
    description: 'Dreaming of snakes is linked to transformation, instinct and the shadow in Jungian psychology. How the snake’s color, behavior and your feelings change the meaning.',
    keywords: ['snake dream meaning', 'dreaming of snakes', 'snake bite dream', 'black snake dream', 'killing a snake dream'],
    symbol: '🐍',
    sections: [
      { h: K, p: ['In Jungian terms, a snake often stands for transformation, repressed instincts and powerful energy rising from the unconscious. Because snakes shed their skin, they are also tied to letting go of the old.', 'It is not a prophecy: the meaning depends on how you felt about the snake and what is changing in your life right now.'] },
      { h: 'The snake in Jung and Freud', p: ['Freud often read the snake as a sexual symbol. Jung saw it as one of humanity’s oldest symbols, carrying both danger and healing (think of the snake on the medical staff) and closely tied to the shadow: a part of us we fear but have not yet accepted.'] },
      { h: S, ul: ['Being bitten: an ignored feeling or truth forcing its way into awareness.', 'Running from a snake: avoiding a change or confrontation.', 'A snake shedding its skin: one chapter closing and another beginning.', 'A calm, harmless snake: a more peaceful relationship with your instincts and body.', 'Many snakes: several worries at once, or scattered energy.'] },
      { h: Q, ul: ['What did I feel when I saw the snake: fear, curiosity, awe?', 'Is there an area of my life where I need to “shed my skin”?'] },
    ],
    related: ['being-chased-dream-meaning', 'death-dream-meaning', 'water-dream-meaning'],
  },
  {
    slug: 'falling-dream-meaning',
    tr: 'ruyada-dusmek',
    title: 'Falling Dream Meaning: Why You Dream of Falling',
    description: 'Falling is one of the most common dreams. Its link to loss of control, anxiety and transitions, why you jolt awake, and how Jung would read it.',
    keywords: ['falling dream meaning', 'dreaming of falling', 'falling off a cliff dream', 'why do i dream of falling', 'hypnic jerk dream'],
    symbol: '🌀',
    sections: [
      { h: K, p: ['Falling dreams usually reflect a sense of losing control or footing: in work, a relationship or a decision. They are especially common during stressful transitions.', 'The jolt you feel when “landing” is often a hypnic jerk, a normal muscle twitch as you fall asleep, not a warning.'] },
      { h: 'A psychological view', p: ['Jung suggested falling dreams can compensate for an attitude that has become too “high”: too much pride, too many expectations or living too much in your head. The dream brings you back to the ground.'] },
      { h: S, ul: ['Falling and waking before impact: an anxiety that hasn’t played out yet.', 'Being pushed: feeling someone else is causing you to lose control.', 'Falling slowly or floating: letting go, more acceptance than fear.', 'Falling from a building at work: pressure around your role or performance.'] },
      { h: Q, ul: ['Where in my life do I feel I’m losing my footing?', 'Am I holding myself to expectations that are too high?'] },
    ],
    related: ['flying-dream-meaning', 'teeth-falling-out-dream-meaning', 'exam-dream-meaning'],
  },
  {
    slug: 'being-chased-dream-meaning',
    tr: 'ruyada-kovalanmak',
    title: 'Being Chased in a Dream: What It Means',
    description: 'Dreams of being chased are among the most common anxiety dreams. Who or what chases you, and why turning around to face it changes everything.',
    keywords: ['being chased dream meaning', 'dream of being chased', 'running away in a dream', 'chased by someone dream', 'chased by a monster dream'],
    symbol: '🏃',
    sections: [
      { h: K, p: ['Being chased usually points to something you are avoiding: a feeling, a conversation, a responsibility or a part of yourself.', 'The chaser is often less important than the question: what am I running from?'] },
      { h: 'Jung and the shadow', p: ['In Jungian psychology the pursuer is often the shadow: qualities we reject in ourselves. Jung noted that when the dreamer stops and faces the pursuer, the figure often becomes less threatening, or even helpful.'] },
      { h: S, ul: ['Chased by a stranger: an unknown or unacknowledged side of yourself.', 'Chased by someone you know: tension with that person or what they represent.', 'Chased by an animal: instincts or emotions you are trying to control.', 'Unable to run: feeling stuck or powerless in a situation.', 'Hiding successfully: postponing a confrontation, for now.'] },
      { h: Q, ul: ['What am I avoiding right now?', 'If I turned around, what would the pursuer want to tell me?'] },
    ],
    related: ['snake-dream-meaning', 'falling-dream-meaning', 'being-late-dream-meaning'],
  },
  {
    slug: 'teeth-falling-out-dream-meaning',
    tr: 'ruyada-dis-dokulmesi',
    title: 'Teeth Falling Out Dream Meaning',
    description: 'Dreaming that your teeth fall out, crumble or break is extremely common. Its link to appearance anxiety, loss of control and life transitions.',
    keywords: ['teeth falling out dream meaning', 'dream teeth crumbling', 'losing teeth dream', 'broken teeth dream', 'tooth falling out dream'],
    symbol: '🦷',
    sections: [
      { h: K, p: ['Teeth dreams often reflect worries about how others see you, losing control, or fear of saying the wrong thing. They are common during big changes like a new job, a breakup or a move.', 'They do not predict death or illness, despite what some folk interpretations say.'] },
      { h: 'A psychological view', p: ['Teeth are about confidence (a smile), power (biting) and growing up (losing baby teeth). Freud tied these dreams to anxiety and repressed wishes; a Jungian reading sees them as a transition where something old must go.'] },
      { h: S, ul: ['Teeth crumbling in your hand: a slow loss of confidence or control.', 'One tooth falling out: a specific change or loss.', 'Hiding your teeth: fear of being seen as weak or imperfect.', 'New teeth growing in: renewal after a hard period.'] },
      { h: Q, ul: ['Where do I worry about how I come across?', 'What is ending or changing in my life right now?'] },
    ],
    related: ['naked-in-public-dream-meaning', 'exam-dream-meaning', 'falling-dream-meaning'],
  },
  {
    slug: 'water-dream-meaning',
    tr: 'ruyada-su-gormek',
    title: 'Water Dream Meaning: Oceans, Floods and Drowning in Dreams',
    description: 'Water is one of the strongest dream symbols for emotion and the unconscious. What calm water, waves, floods and drowning dreams can mean.',
    keywords: ['water dream meaning', 'ocean dream meaning', 'flood dream meaning', 'drowning dream meaning', 'swimming dream meaning'],
    symbol: '🌊',
    sections: [
      { h: K, p: ['Water in dreams usually mirrors your emotional state: calm water for inner peace, rough waves or floods for overwhelming feelings.', 'Jung saw large bodies of water, especially the sea, as the classic image of the unconscious.'] },
      { h: 'Jung’s view', p: ['For Jung, going into water is going into the depths of the psyche. It can feel threatening, but it is also where renewal comes from: many myths of rebirth begin in water.'] },
      { h: S, ul: ['Swimming easily: being at ease with your feelings.', 'Huge waves or a tsunami: an emotion or event that feels too big to handle.', 'A flood in your house: feelings spilling into your private life.', 'Drowning: being overwhelmed by emotions or responsibilities.', 'Clear, still water: clarity and calm.'] },
      { h: Q, ul: ['Are my emotions mostly calm or stormy lately?', 'Is there a feeling I keep “keeping my head above”?'] },
    ],
    related: ['flying-dream-meaning', 'snake-dream-meaning', 'pregnancy-dream-meaning'],
  },
  {
    slug: 'flying-dream-meaning',
    tr: 'ruyada-ucmak',
    title: 'Flying Dream Meaning: Why You Dream of Flying',
    description: 'Flying dreams are often joyful, sometimes frightening. What they say about freedom, ambition and perspective, and their link to lucid dreaming.',
    keywords: ['flying dream meaning', 'dreaming of flying', 'flying in a dream', 'can’t fly high dream', 'lucid flying dream'],
    symbol: '🕊️',
    sections: [
      { h: K, p: ['Flying usually expresses freedom, rising above a problem or seeing your life from a wider perspective. It is one of the most common triggers for lucid dreams.', 'When flying is hard, too low or scary, it often reflects doubt about an ambition.'] },
      { h: 'A psychological view', p: ['Jung warned that flying can also compensate for feeling powerless in waking life, or signal an attitude that has drifted too far from the ground. The feeling in the dream tells you which one it is.'] },
      { h: S, ul: ['Soaring freely: confidence, relief and freedom.', 'Struggling to stay up: effort and doubt around a goal.', 'Flying away from danger: escaping a stressful situation.', 'Fear of heights while flying: anxiety about success or exposure.'] },
      { h: Q, ul: ['What would I like to rise above right now?', 'Is my ambition grounded in what I really want?'] },
    ],
    related: ['falling-dream-meaning', 'water-dream-meaning', 'lucid-dreaming-guide'],
  },
  {
    slug: 'death-dream-meaning',
    tr: 'ruyada-olum-gormek',
    title: 'Death Dream Meaning: Dreaming of Dying or Someone’s Death',
    description: 'Dreams about death are rarely about literal death. They usually point to endings, transformation and change. What dreaming of your own or a loved one’s death means.',
    keywords: ['death dream meaning', 'dreaming of dying', 'dream about someone dying', 'dream about my own death', 'dead loved one dream'],
    symbol: '🕯️',
    sections: [
      { h: K, p: ['In dreams, death almost always symbolizes an ending: a phase of life, a relationship, a habit or an old version of yourself. Something ends so that something new can begin.', 'These dreams are not predictions.'] },
      { h: 'Jung’s view', p: ['Jung saw death in dreams as part of a cycle of death and rebirth: the ego letting go of an old identity. Dreaming of a deceased loved one is also a natural part of grief.'] },
      { h: S, ul: ['Your own death: a big transformation or identity change.', 'A loved one dying: fear of losing them, or a change in your relationship.', 'Talking to someone who has died: longing, unfinished words or seeking guidance.', 'Attending a funeral: saying goodbye to a phase of life.'] },
      { h: Q, ul: ['What is ending in my life right now?', 'What part of me is ready to be left behind?'] },
    ],
    related: ['snake-dream-meaning', 'ex-dream-meaning', 'pregnancy-dream-meaning'],
  },
  {
    slug: 'ex-dream-meaning',
    tr: 'ruyada-eski-sevgiliyi-gormek',
    title: 'Dreaming About Your Ex: What It Really Means',
    description: 'Dreaming about an ex doesn’t necessarily mean you want them back. What these dreams say about unfinished feelings, patterns and your current relationship.',
    keywords: ['dreaming about your ex', 'ex dream meaning', 'dream about ex boyfriend', 'dream about ex girlfriend', 'why do i dream about my ex'],
    symbol: '💔',
    sections: [
      { h: K, p: ['Dreaming of an ex is usually less about them and more about what that relationship meant: a version of yourself, a lesson, or an unresolved feeling.', 'These dreams often show up when a new relationship begins or when something reminds you of an old pattern.'] },
      { h: 'A psychological view', p: ['From a Jungian view, the ex can represent the anima or animus, your inner image of the other, or a quality you lost or gave away in that relationship.'] },
      { h: S, ul: ['Getting back together: wanting a feeling or part of yourself back, not necessarily the person.', 'Arguing with your ex: unprocessed anger or unsaid words.', 'Your ex with someone new: comparison or fear of being replaced.', 'A friendly conversation: acceptance and closure.'] },
      { h: Q, ul: ['What did I feel in that relationship that I’m missing now?', 'Am I repeating a pattern?'] },
    ],
    related: ['wedding-dream-meaning', 'death-dream-meaning', 'being-chased-dream-meaning'],
  },
  {
    slug: 'being-late-dream-meaning',
    tr: 'ruyada-sinava-girmek',
    title: 'Being Late Dream Meaning: Missing the Bus, Plane or Exam',
    description: 'Dreams of running late, missing a flight or a train are classic stress dreams. What they say about pressure, fear of missing out and self-expectations.',
    keywords: ['being late dream meaning', 'missing a flight dream', 'missing the bus dream', 'running late dream', 'late for work dream'],
    symbol: '⏰',
    sections: [
      { h: K, p: ['Being late in a dream usually reflects time pressure, an overloaded schedule or fear of missing an opportunity.', 'They often come in busy periods, before a deadline or a big decision.'] },
      { h: 'A psychological view', p: ['These dreams can also point to a conflict: part of you may not actually want to arrive. Missing the train can be a way of avoiding a destination you are unsure about.'] },
      { h: S, ul: ['Missing a flight: anxiety about a big change or opportunity.', 'Clock moving too fast: feeling life is moving faster than you can keep up.', 'Can’t find what you need to leave: feeling unprepared.', 'Arriving just in time: relief, you can handle more than you think.'] },
      { h: Q, ul: ['Where do I feel “behind” in life?', 'Do I really want to get where I’m rushing to?'] },
    ],
    related: ['exam-dream-meaning', 'falling-dream-meaning', 'lost-phone-dream-meaning'],
  },
  {
    slug: 'exam-dream-meaning',
    tr: 'ruyada-sinava-girmek',
    title: 'Exam Dream Meaning: Unprepared for a Test',
    description: 'Long after school, many people still dream of exams they didn’t study for. How these dreams reflect performance anxiety and fear of being judged.',
    keywords: ['exam dream meaning', 'unprepared for exam dream', 'failing a test dream', 'school dream meaning', 'can’t find the exam room dream'],
    symbol: '📝',
    sections: [
      { h: K, p: ['Exam dreams typically reflect performance anxiety, fear of being judged or a feeling of “I’m not ready.” They appear when you feel tested at work or in a relationship.'] },
      { h: 'A psychological view', p: ['Freud noted that people often dream of exams they actually passed, as if the mind reassures itself: “You managed it before, you’ll manage now.”'] },
      { h: S, ul: ['Unprepared for the exam: inadequacy around a new responsibility.', 'Can’t find the exam room: unclear goals or direction.', 'Blank paper: fear of not being able to express yourself.', 'Passing easily: inner confidence you may be overlooking.'] },
      { h: Q, ul: ['Where do I feel tested right now?', 'Who sets my standard for success?'] },
    ],
    related: ['being-late-dream-meaning', 'teeth-falling-out-dream-meaning', 'naked-in-public-dream-meaning'],
  },
  {
    slug: 'house-dream-meaning',
    tr: 'ruyada-ev-gormek',
    title: 'House Dream Meaning: Rooms, Old Homes and Hidden Doors',
    description: 'For Jung, a house in a dream represents the self. What it means to find a hidden room, return to a childhood home, or see a house collapse.',
    keywords: ['house dream meaning', 'dream about childhood home', 'finding a hidden room dream', 'house collapsing dream', 'moving house dream'],
    symbol: '🏠',
    sections: [
      { h: K, p: ['A house in a dream usually represents your inner world and personality. Floors and rooms can be read as different layers of the self.'] },
      { h: 'Jung’s famous house dream', p: ['Jung based part of his idea of the collective unconscious on his own dream of a house: the upper floor was the conscious mind, and each lower level was older and more collective. Basement dreams can point to deep content.'] },
      { h: S, ul: ['Discovering a new room: a potential you haven’t noticed.', 'Childhood home: a return to roots and old patterns.', 'A house collapsing: shaken sense of security.', 'Moving house: a life transition.', 'Dark basement: the unconscious, unexplored material.'] },
      { h: Q, ul: ['Which “rooms” of my life have I been avoiding?', 'Where do I feel truly at home?'] },
    ],
    related: ['death-dream-meaning', 'water-dream-meaning', 'pregnancy-dream-meaning'],
  },
  {
    slug: 'wedding-dream-meaning',
    tr: 'ruyada-dugun-gormek',
    title: 'Wedding Dream Meaning: Dreaming of Getting Married',
    description: 'Wedding dreams are rarely about a literal marriage. They point to commitment, union and a new chapter. Jung’s view and common scenarios.',
    keywords: ['wedding dream meaning', 'dreaming of getting married', 'wedding dress dream', 'marrying a stranger dream', 'marrying your ex dream'],
    symbol: '💍',
    sections: [
      { h: K, p: ['A wedding in a dream usually means committing to something: a decision, a job, an idea or a new chapter, and bringing two parts of yourself together.', 'Whether you felt happy or anxious is the main clue to the meaning.'] },
      { h: 'Jung’s sacred marriage', p: ['Jung read the wedding as the union of opposites (coniunctio): conscious and unconscious, reason and emotion, anima and animus. It can mark a process of becoming whole.'] },
      { h: S, ul: ['Happy at your own wedding: wholeheartedly accepting a new phase.', 'Wanting to run away: hesitation about a commitment.', 'Marrying a stranger: uniting with a newly discovered side of yourself.', 'Marrying your ex: an unfinished feeling or a lost part of you.', 'Cancelled wedding: worry that plans will change.'] },
      { h: Q, ul: ['What am I about to say “yes” to?', 'Is this commitment truly mine?'] },
    ],
    related: ['ex-dream-meaning', 'pregnancy-dream-meaning', 'money-dream-meaning'],
  },
  {
    slug: 'money-dream-meaning',
    tr: 'ruyada-para-gormek',
    title: 'Money Dream Meaning: Finding or Losing Money in a Dream',
    description: 'Dreams about finding, losing or counting money are about value, security and where your energy goes, not a forecast of wealth.',
    keywords: ['money dream meaning', 'finding money dream', 'losing money dream', 'dream about cash', 'counting money dream'],
    symbol: '💰',
    sections: [
      { h: K, p: ['Money in dreams is usually about value: how much you value yourself, whether your effort is rewarded, and how secure you feel.', 'It is not a prediction of wealth or poverty; what you do with the money and how you feel matter most.'] },
      { h: 'Freud and Jung on money', p: ['Freud linked money to possession and control. For Jung, money can symbolize psychic energy: where you spend money in a dream may show where your energy goes in life.'] },
      { h: S, ul: ['Finding money: an overlooked talent or opportunity.', 'Losing money: fear of losing status, control or confidence.', 'Giving money away: sharing your time and care, or giving too much.', 'Counting money: weighing what is “enough” in your life.', 'Fake money: a sense that something isn’t as valuable as it looks.'] },
      { h: Q, ul: ['Where do I feel undervalued lately?', 'Am I spending my energy on what truly matters to me?'] },
    ],
    related: ['lost-phone-dream-meaning', 'wedding-dream-meaning', 'house-dream-meaning'],
  },
  {
    slug: 'pregnancy-dream-meaning',
    tr: 'ruyada-hamile-olmak',
    title: 'Pregnancy Dream Meaning: Dreaming You Are Pregnant',
    description: 'Dreaming of being pregnant rarely means an actual pregnancy. It usually points to an idea, project or new phase growing inside you.',
    keywords: ['pregnancy dream meaning', 'dreaming of being pregnant', 'giving birth dream', 'man dreaming of pregnancy', 'someone else pregnant dream'],
    symbol: '🤰',
    sections: [
      { h: K, p: ['Pregnancy dreams usually describe something slowly developing within you: a new idea, a project, a relationship or an identity. That is why men have these dreams too.', 'Real hopes or worries about pregnancy can also show up; the symbolic meaning is usually broader.'] },
      { h: 'Jung’s view', p: ['For Jung, pregnancy in a dream is new content forming in the unconscious and preparing to be “born” into awareness: a potential you haven’t named yet.'] },
      { h: S, ul: ['Happy to be pregnant: readiness for a new start.', 'Scared to be pregnant: worry about responsibility or change.', 'Giving birth: something long prepared is ready to come out.', 'Someone else is pregnant: something new starting around you.'] },
      { h: Q, ul: ['What idea is growing inside me that I haven’t shared?', 'Do I feel ready for a new responsibility?'] },
    ],
    related: ['wedding-dream-meaning', 'water-dream-meaning', 'death-dream-meaning'],
  },
  {
    slug: 'lost-phone-dream-meaning',
    tr: 'ruyada-telefon-kaybetmek',
    title: 'Lost Phone Dream Meaning: Can’t Call Anyone in a Dream',
    description: 'Losing your phone, a cracked screen or not being able to dial a number are modern anxiety dreams about connection, communication and control.',
    keywords: ['lost phone dream meaning', 'can’t dial phone dream', 'broken phone dream', 'phone stolen dream', 'phone not working dream'],
    symbol: '📱',
    sections: [
      { h: K, p: ['Phones have become the modern symbol of connection and control. Losing yours, or not being able to call, often reflects a fear of not being able to reach someone or not being understood.', 'Heavy daytime phone use also feeds these dreams, so they don’t always carry deep meaning.'] },
      { h: 'A psychological view', p: ['A phone that won’t work is a modern version of the classic “can’t call for help” dream. The phone is also an extension of identity and social network; losing it can touch a fear of losing yourself.'] },
      { h: S, ul: ['Losing your phone: loss of connection or control.', 'Can’t dial the number: wanting to say something but being unable to.', 'Cracked screen: a break or tension in communication.', 'Phone stolen: feeling your privacy has been violated.', 'Feeling relieved without a phone: wanting a break from always being reachable.'] },
      { h: Q, ul: ['Is there someone I want to reach but can’t?', 'Is being constantly connected exhausting me?'] },
    ],
    related: ['being-late-dream-meaning', 'money-dream-meaning', 'naked-in-public-dream-meaning'],
  },
  {
    slug: 'naked-in-public-dream-meaning',
    tr: 'ruyada-ciplak-olmak',
    title: 'Naked in Public Dream Meaning',
    description: 'Being naked in front of others is one of the most common anxiety dreams. Its link to fear of exposure, vulnerability and authenticity.',
    keywords: ['naked in public dream meaning', 'dream of being naked', 'naked dream meaning', 'can’t find clothes dream', 'exposed in a dream'],
    symbol: '🫣',
    sections: [
      { h: K, p: ['Nudity dreams usually reflect a fear of being exposed: caught unprepared, a flaw being seen, or being judged.', 'Interestingly, in many of these dreams nobody notices; the shame is mostly inside us.'] },
      { h: 'Freud and Jung', p: ['Freud connected these dreams to a wish to return to a childhood without shame. For Jung, nakedness is the persona, the social mask, falling away so the real self is visible; frightening, but also freeing.'] },
      { h: S, ul: ['Naked and ashamed: fear of looking inadequate in a new role.', 'Naked and nobody notices: a reminder that you draw less attention than you fear.', 'Naked and comfortable: accepting yourself as you are.', 'Searching for clothes: losing your usual ways of protecting yourself.'] },
      { h: Q, ul: ['Where do I feel “too visible” right now?', 'Is there a part of me I keep hiding?'] },
    ],
    related: ['teeth-falling-out-dream-meaning', 'exam-dream-meaning', 'being-chased-dream-meaning'],
  },
  {
    slug: 'lucid-dreaming-guide',
    tr: 'lucid-ruya-nasil-gorulur',
    title: 'Lucid Dreaming for Beginners: How to Become Aware in Your Dreams',
    description: 'Lucid dreaming means knowing you are dreaming while still in the dream. Simple, evidence-informed techniques: dream journals, reality checks and MILD.',
    keywords: ['lucid dreaming', 'how to lucid dream', 'lucid dreaming techniques', 'reality check lucid dream', 'MILD technique'],
    symbol: '🌙',
    sections: [
      { h: K, p: ['A lucid dream is a dream in which you realize you are dreaming. Some people can then steer the dream; others simply observe with more clarity.', 'Most people can learn it with practice, and the first step is remembering your dreams.'] },
      { h: 'Techniques that help', ul: ['Keep a dream journal: write every dream right after waking, even fragments.', 'Reality checks: several times a day ask “Am I dreaming?” and check something, like reading a line of text twice.', 'MILD: as you fall asleep, repeat “Next time I’m dreaming, I’ll notice I’m dreaming.”', 'Wake back to bed: wake briefly after 5–6 hours of sleep, then go back to sleep with the intention to become lucid.'] },
      { h: 'A note on sleep', p: ['Don’t sacrifice healthy sleep for lucid dreaming. If you have sleep problems, talk to a professional.'] },
    ],
    related: ['flying-dream-meaning', 'falling-dream-meaning', 'being-chased-dream-meaning'],
  },
]

export function getGuideEn(slug) {
  return DREAM_GUIDES_EN.find((g) => g.slug === slug) || null
}
