// İkinci parti rüya rehberleri (2026-10-06). Format dreamGuides.js ile aynı;
// DREAM_GUIDES dizisine oradan eklenir. Ton: kehanet değil, Freud + Jung'cu,
// öznel yorum; her yazı kişisel bağlamın anlamı değiştirdiğini vurgular.

const Q = 'Kendine sorabileceğin sorular'
const S = 'Farklı senaryolar'
const K = 'Kısa cevap'

export const MORE_DREAM_GUIDES = [
  {
    slug: 'ruyada-para-gormek',
    title: 'Rüyada Para Görmek Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada para bulmak, kaybetmek ya da para saymak; öz değer, güvenlik ihtiyacı ve hayatına ne kadar enerji verdiğinle ilişkili olabilir. Freud ve Jung’a göre yorumu.',
    keywords: ['rüyada para görmek', 'rüyada para bulmak', 'rüyada para kaybetmek', 'rüyada kağıt para görmek', 'rüyada bozuk para görmek', 'rüyada para saymak'],
    symbol: '💰',
    sections: [
      { h: K, p: ['Rüyadaki para çoğu zaman gerçek paradan çok “değer” hissini anlatır: kendine ne kadar değer verdiğini, emeğinin karşılığını alıp almadığını ve kendini ne kadar güvende hissettiğini.', 'Bu bir zenginlik ya da yoksulluk kehaneti değildir; anlamı, rüyada parayla ne yaptığına ve o an ne hissettiğine bağlıdır.'] },
      { h: 'Freud ve Jung’a göre para', p: ['Freud parayı sahip olma, biriktirme ve kontrol arzusuyla ilişkilendirir. Jung’cu bakışta ise para psişik enerjinin bir sembolüdür: Parayı nereye harcıyorsan, hayatında enerjini de oraya veriyor olabilirsin.'] },
      { h: S, ul: ['Yerde para bulmak: Fark etmediğin bir yeteneğin ya da fırsatın ortaya çıkması.', 'Para kaybetmek: Kontrolü, statüyü ya da öz güveni kaybetme kaygısı.', 'Birine para vermek: Emeğini, zamanını veya sevgini paylaşma isteği; bazen de fazla verip tükenme.', 'Para saymak: Hayatında neyin “yeterli” olduğunu tartma ihtiyacı.', 'Sahte para: Bir ilişkide ya da işte değerin gerçek olmadığı hissi.'] },
      { h: Q, ul: ['Son zamanlarda değerimin görülmediğini hissettiğim bir yer var mı?', 'Enerjimi gerçekten önemsediğim şeylere mi harcıyorum?', 'Güvende hissetmek için neye ihtiyacım var?'] },
    ],
    related: ['ruyada-altin-gormek', 'ruyada-telefon-kaybetmek', 'jung-arketipleri-rehberi'],
  },
  {
    slug: 'ruyada-altin-gormek',
    title: 'Rüyada Altın Görmek Ne Anlama Gelir? Jung’a Göre Yorumu',
    description: 'Rüyada altın bulmak, takmak ya da kaybetmek; içsel değer, benliğin özü ve dönüşümle ilişkilendirilir. Simyadan Jung’a altın sembolü.',
    keywords: ['rüyada altın görmek', 'rüyada altın bulmak', 'rüyada altın takmak', 'rüyada altın kaybetmek', 'rüyada altın bilezik görmek', 'altın rüya tabiri'],
    symbol: '🪙',
    sections: [
      { h: K, p: ['Altın, rüyalarda çoğu zaman kalıcı ve gerçek değeri temsil eder: içindeki en kıymetli yan, kolay kolay paslanmayan bir değer ya da uzun süredir aradığın bir anlam.', 'Bir servet kehaneti olarak değil, kendinde neyi değerli bulduğuna dair bir işaret olarak okumak daha yararlıdır.'] },
      { h: 'Jung ve simyadaki altın', p: ['Jung, simyacıların “kurşunu altına çevirme” hayalini psikolojik bir dönüşümün dili olarak okur: Ham, karanlık malzemenin işlenerek benliğin özüne ulaşması. Rüyada altın bulmak, bu iç çalışmanın bir aşamasına işaret edebilir.'] },
      { h: S, ul: ['Toprağın altında altın bulmak: Derinlerde, bilinçdışında saklı bir değeri keşfetmek.', 'Altın takı takmak: Görünür olma, değer görme ya da bir bağlılık (ör. aile, ilişki) hissi.', 'Altın kaybetmek: Önemli bir şeyi koruyamama kaygısı.', 'Altın hediye almak: Birinin sende gördüğü değeri kabul etmek.', 'Sahte altın: Parlak görünen ama içi boş bir şeyle ilgili şüphe.'] },
      { h: Q, ul: ['Hayatımda kalıcı değer verdiğim şey ne?', 'Değerli bulduğum bir yanımı saklıyor muyum?'] },
    ],
    related: ['ruyada-para-gormek', 'ruyada-dugun-gormek', 'jung-arketipleri-rehberi'],
  },
  {
    slug: 'ruyada-sac-kesmek',
    title: 'Rüyada Saç Kesmek ve Saç Dökülmesi Ne Anlama Gelir?',
    description: 'Rüyada saç kestirmek, saçın dökülmesi ya da uzaması; kimlik, değişim isteği ve kontrol duygusuyla ilişkilidir. Psikolojik yorumu ve farklı senaryolar.',
    keywords: ['rüyada saç kesmek', 'rüyada saç dökülmesi', 'rüyada saç kestirmek', 'rüyada saçın uzaması', 'rüyada kel olmak', 'saç rüya tabiri'],
    symbol: '✂️',
    sections: [
      { h: K, p: ['Saç, kişinin dışarıya gösterdiği kimliğin ve kendini ifade etme biçiminin güçlü bir sembolüdür. Rüyada saç kesmek çoğu zaman bir değişim isteğini; saçın dökülmesi ise kontrol ya da çekicilik kaybı kaygısını yansıtır.', 'Rüyada saçına ne olduğu kadar, bunu senin mi yoksa başkasının mı yaptığı da yorumu değiştirir.'] },
      { h: 'Psikolojik bakış', p: ['Freud saç kesmeyi güç ve kontrol kaybıyla ilişkilendirir. Jung’cu bakışta ise saç, kişinin “persona”sının, yani dünyaya gösterdiği yüzün parçasıdır; saçı kesmek eski bir rolü bırakıp yenisini denemek anlamına gelebilir.'] },
      { h: S, ul: ['Kendi saçını kendin kesmek: Hayatında bilinçli bir değişim başlatma isteği.', 'Başkasının saçını zorla kesmesi: Biri ya da bir durum seni istemediğin bir şekle sokuyor olabilir.', 'Saçın tutam tutam dökülmesi: Yaşlanma, güç ya da kontrol kaybı kaygısı.', 'Saçın birden uzaması: Gelişme, canlılık ve kendine yeniden güven.', 'Saçını beğenmemek: Başkalarının seni nasıl gördüğüne dair kaygı.'] },
      { h: Q, ul: ['Şu an hayatımda değiştirmek istediğim ama cesaret edemediğim ne var?', 'Kendimi nasıl gösterdiğim konusunda kimin onayını bekliyorum?'] },
    ],
    related: ['ruyada-dis-dokulmesi', 'ruyada-ciplak-olmak', 'ruyada-dugun-gormek'],
  },
  {
    slug: 'ruyada-dugun-gormek',
    title: 'Rüyada Düğün Görmek ve Evlenmek Ne Anlama Gelir?',
    description: 'Rüyada evlenmek, gelinlik giymek ya da birinin düğününe gitmek; bağlılık, birleşme ve hayatında yeni bir döneme geçişle ilişkilidir. Jung’a göre yorumu.',
    keywords: ['rüyada düğün görmek', 'rüyada evlenmek', 'rüyada gelinlik giymek', 'rüyada düğüne gitmek', 'rüyada eski sevgiliyle evlenmek', 'rüyada nişan görmek'],
    symbol: '💍',
    sections: [
      { h: K, p: ['Düğün rüyaları her zaman gerçek bir evliliği anlatmaz. Çoğu zaman bir karara, işe, fikre ya da yeni bir hayat dönemine “bağlanma” halini ve iki farklı yanının birleşmesini temsil eder.', 'Rüyada mutlu muydun, kaygılı mı? Bu his, yorumun yönünü belirleyen en önemli ipucudur.'] },
      { h: 'Jung’da kutsal evlilik', p: ['Jung, düğünü karşıtların birleşmesi (coniunctio) olarak okur: Bilinçli yanınla bilinçdışı yanının, mantığınla duygunun ya da anima ve animus’un buluşması. Bu yüzden düğün rüyası bir bütünleşme sürecine işaret edebilir.'] },
      { h: S, ul: ['Kendi düğününde mutlu olmak: Bir kararı ya da yeni bir dönemi içten kabul etmek.', 'Düğünde kaygılı ya da kaçmak isteyen olmak: Bir bağlılıktan duyulan tereddüt.', 'Tanımadığın biriyle evlenmek: Kendinde yeni tanıdığın bir yanla birleşmek.', 'Eski sevgiliyle evlenmek: Kapanmamış bir duygu ya da o ilişkide kaybettiğin bir yanını geri isteme.', 'Düğünün iptal olması: Planların ya da beklentilerin değişeceği kaygısı.'] },
      { h: Q, ul: ['Şu an neye “evet” demek üzereyim?', 'Bu bağlılık bana mı ait, yoksa beklentilere mi?'] },
    ],
    related: ['ruyada-eski-sevgiliyi-gormek', 'ruyada-hamile-olmak', 'jung-arketipleri-rehberi'],
  },
  {
    slug: 'ruyada-araba-kullanmak',
    title: 'Rüyada Araba Kullanmak Ne Anlama Gelir? Kontrol ve Yön',
    description: 'Rüyada araba kullanmak, frenin tutmaması, kaza yapmak ya da arka koltukta oturmak; hayatının direksiyonunda kimin olduğuyla ilgilidir.',
    keywords: ['rüyada araba kullanmak', 'rüyada araba kazası', 'rüyada fren tutmaması', 'rüyada araba görmek', 'rüyada arabanın çalınması', 'rüyada arka koltukta oturmak'],
    symbol: '🚗',
    sections: [
      { h: K, p: ['Araba rüyaları çoğunlukla hayatının yönünü ve kontrolünü anlatır: direksiyonda sen misin, nereye gidiyorsun ve hız sana uygun mu?', 'Bu rüyalar gerçek bir kaza uyarısı değildir; günlük hayattaki kontrol hissini yansıtır.'] },
      { h: 'Psikolojik bakış', p: ['Modern rüyalarda araba, eski rüyalardaki at ya da yolculuk sembolünün yerini almıştır: kişinin hayatta ilerleme biçimi. Jung’cu bakışta arabanın kendisi egoyu, gidilen yol ise yaşam sürecini temsil edebilir.'] },
      { h: S, ul: ['Frenin tutmaması: Bir durumun hızına yetişememe, durduramama kaygısı.', 'Arka koltukta oturmak: Hayatının kararlarını başkasının veriyor olması.', 'Kaza yapmak: Bir planın, ilişkinin ya da tempo’nun çarpışma rotasında olduğu hissi.', 'Yolu kaybetmek: Yön ya da hedef belirsizliği.', 'Rahatça, keyifle sürmek: Hayatının kontrolünün sende olduğuna dair iç güven.'] },
      { h: Q, ul: ['Hayatımın hangi alanında direksiyon bende değil?', 'Gereğinden hızlı mı ilerliyorum?'] },
    ],
    related: ['ruyada-kaybolmak', 'ruyada-ucak-gormek', 'ruyada-kovalanmak'],
  },
  {
    slug: 'ruyada-hamile-olmak',
    title: 'Rüyada Hamile Olmak Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada hamile olduğunu görmek çoğu zaman gerçek bir gebeliği değil, içinde büyüyen bir fikri, projeyi ya da yeni bir dönemi temsil eder.',
    keywords: ['rüyada hamile olmak', 'rüyada hamile olduğunu görmek', 'rüyada hamile kadın görmek', 'rüyada doğum yapmak', 'erkeğin rüyada hamile olması', 'hamilelik rüyası ne demek'],
    symbol: '🤰',
    sections: [
      { h: K, p: ['Hamilelik rüyası, çoğu zaman içinde yavaş yavaş gelişen bir şeyi anlatır: yeni bir fikir, proje, ilişki ya da kimlik. Erkeklerin de bu rüyayı görmesi bu yüzden çok yaygındır.', 'Gerçek bir gebelikle ilgili kaygı ya da istek de rüyaya yansıyabilir; ama sembolik anlamı genellikle daha geniştir.'] },
      { h: 'Jung’cu bakış', p: ['Jung’a göre gebelik, bilinçdışında oluşan yeni bir içeriğin bilince doğmaya hazırlanmasıdır. Bu, kendinde henüz adını koymadığın bir potansiyelin “taşınması” gibidir.'] },
      { h: S, ul: ['Hamile olduğunu öğrenip sevinmek: Yeni bir başlangıca hazır olmak.', 'Hamile olup korkmak: Sorumluluk alma ya da hayatın değişmesi kaygısı.', 'Doğum yapmak: Uzun süredir hazırladığın bir şeyin artık dünyaya çıkması.', 'Başka birinin hamile olduğunu görmek: Çevrendeki birinde ya da ilişkinizde yeni bir şeyin başlaması.', 'Hamileliğin bitmemesi: Bir projenin sürekli ertelenmesi.'] },
      { h: Q, ul: ['İçimde büyüyen, henüz kimseye göstermediğim bir fikir var mı?', 'Yeni bir sorumluluğa hazır hissediyor muyum?'] },
    ],
    related: ['ruyada-bebek-gormek', 'ruyada-dugun-gormek', 'ruyada-anne-gormek'],
  },
  {
    slug: 'ruyada-olmus-birini-gormek',
    title: 'Rüyada Ölmüş Birini Görmek Ne Anlama Gelir?',
    description: 'Rüyada ölmüş bir yakını görmek, onunla konuşmak ya da sarılmak; yas süreci, özlem ve tamamlanmamış duygularla ilişkilidir. Psikolojik yorumu.',
    keywords: ['rüyada ölmüş birini görmek', 'rüyada ölmüş annemi görmek', 'rüyada ölmüş babamı görmek', 'rüyada ölü ile konuşmak', 'rüyada ölmüş birinin canlı olması', 'rüyada ölüye sarılmak'],
    symbol: '🕯️',
    sections: [
      { h: K, p: ['Kaybettiğin birini rüyada görmek, yas sürecinin çok doğal bir parçasıdır. Zihin özlemi, söylenmemiş sözleri ve o kişiyle ilgili anıları rüyada işlemeye devam eder.', 'Bu rüyalar teselli edici de olabilir, sarsıcı da. Rüyadaki atmosfer, yasın şu an hangi aşamasında olduğuna dair ipucu verir.'] },
      { h: 'Psikolojik bakış', p: ['Freud yas rüyalarını kaybı kabullenme çalışmasının bir parçası olarak görür. Jung’cu bakışta ise ölmüş kişi, sende yaşamaya devam eden bir niteliği temsil edebilir: onun bilgeliği, şefkati ya da senin onunla birlikte kaybettiğini sandığın bir yanın.'] },
      { h: S, ul: ['Ölmüş kişinin canlı ve sağlıklı görünmesi: Kabullenme ve iç huzur arayışı.', 'Onunla konuşmak: Söyleyemediklerini söyleme ya da ondan rehberlik isteme ihtiyacı.', 'Sana bir şey vermesi: Ondan sende kalan bir değeri fark etmek.', 'Seni çağırması ya da gitmesi: Ayrılığı kabullenme süreci; bir ölüm kehaneti değildir.', 'Tekrar tekrar görmek: Yasın henüz tamamlanmadığına dair bir işaret.'] },
      { h: Q, ul: ['Ona söylemek isteyip söyleyemediğim bir şey var mı?', 'Ondan bende hangi özellik yaşamaya devam ediyor?'] },
      { h: 'Ne zaman destek almalı?', p: ['Rüyalar uykunu ya da gündelik hayatını uzun süre zorluyorsa, bir yas danışmanı ya da ruh sağlığı uzmanıyla konuşmak iyi gelebilir.'] },
    ],
    related: ['ruyada-olum-gormek', 'tekrarlayan-ruyalarin-anlami', 'ruyada-aglamak'],
  },
  {
    slug: 'ruyada-deprem-olmasi',
    title: 'Rüyada Deprem Olması Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada deprem görmek, binanın sallanması ya da enkaz altında kalmak; hayatındaki ani değişimler ve güven duygusunun sarsılmasıyla ilişkilidir.',
    keywords: ['rüyada deprem olması', 'rüyada deprem görmek', 'rüyada depremden kaçmak', 'rüyada enkaz altında kalmak', 'rüyada bina yıkılması', 'deprem rüyası ne demek'],
    symbol: '🏚️',
    sections: [
      { h: K, p: ['Deprem rüyası, çoğu zaman “sağlam sandığın zeminin” sarsılmasını anlatır: bir ilişki, iş, aile düzeni ya da inanç. Ani bir değişim veya beklenmedik bir haber sonrası sık görülür.', 'Türkiye gibi deprem kaygısının yüksek olduğu yerlerde, gerçek bir korkunun rüyaya yansıması da çok doğaldır; bu bir kehanet değildir.'] },
      { h: 'Psikolojik bakış', p: ['Jung’cu bakışta yer, temeli ve güvenlik duygusunu temsil eder. Deprem, bilinçdışında biriken bir gerilimin yüzeye çıkması ya da eski bir yapının yıkılıp yenisine yer açması olarak okunabilir.'] },
      { h: S, ul: ['Depremden kaçmak: Bir değişimle yüzleşmek yerine ondan uzaklaşma eğilimi.', 'Enkaz altında kalmak: Sorumlulukların ya da kaygıların altında ezilme hissi.', 'Yakınlarını kurtarmak: Sevdiklerini koruma ihtiyacı ve sorumluluk duygusu.', 'Deprem sonrası sakinlik: Zor bir dönemin ardından toparlanma gücü.', 'Sadece hafif sarsıntı: Henüz fark edilen ama büyümemiş bir huzursuzluk.'] },
      { h: Q, ul: ['Hayatımda şu an hangi “zemin” sarsılıyor?', 'Yıkılan şeyin yerine ne kurmak istiyorum?'] },
    ],
    related: ['ruyada-ev-gormek', 'ruyada-yangin-gormek', 'tekrarlayan-ruyalarin-anlami'],
  },
  {
    slug: 'ruyada-yangin-gormek',
    title: 'Rüyada Yangın ve Ateş Görmek Ne Anlama Gelir?',
    description: 'Rüyada ev yangını görmek, ateşi söndürmek ya da yanmak; tutku, öfke ve arınmayla ilişkilidir. Freud ve Jung’a göre ateş sembolü.',
    keywords: ['rüyada yangın görmek', 'rüyada ateş görmek', 'rüyada evin yanması', 'rüyada yangın söndürmek', 'rüyada ateşe düşmek', 'ateş rüya tabiri'],
    symbol: '🔥',
    sections: [
      { h: K, p: ['Ateş hem yakıp yıkan hem ısıtan ve arındıran bir semboldür. Rüyada yangın, kontrolden çıkmış bir duyguyu (öfke, tutku, kıskançlık) ya da eskinin yanıp yeniye yer açmasını anlatabilir.', 'Ateşe karşı hissettiğin duygu, korku mu hayranlık mı, yorumu belirler.'] },
      { h: 'Freud ve Jung’a göre ateş', p: ['Freud ateşi çoğunlukla tutku ve arzuyla ilişkilendirir. Jung ise ateşi dönüşümün ve psişik enerjinin sembolü olarak görür: Simyada malzeme ateşte işlenerek değişir.'] },
      { h: S, ul: ['Evinin yanması: Kimliğinin ya da güvenli alanının köklü bir değişimden geçmesi.', 'Yangını söndürmek: Bir duyguyu kontrol altına alma çabası.', 'Ateşi uzaktan izlemek: Bir değişimin tanığı olmak, henüz içine girmemek.', 'Ocakta sıcak bir ateş: Sıcaklık, yakınlık ve iç enerji.', 'Yanmak: Tükenmişlik ya da bir duygunun seni ele geçirmesi.'] },
      { h: Q, ul: ['İçimde bastırdığım bir öfke ya da tutku var mı?', 'Hayatımda “yanıp bitmesi” gereken eski bir şey var mı?'] },
    ],
    related: ['ruyada-deprem-olmasi', 'ruyada-su-gormek', 'jung-arketipleri-rehberi'],
  },
  {
    slug: 'ruyada-kan-gormek',
    title: 'Rüyada Kan Görmek Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada kan görmek, kanamak ya da başkasının kanını görmek; yaşam enerjisi, duygusal yara ve tükenmişlikle ilişkilidir.',
    keywords: ['rüyada kan görmek', 'rüyada kanamak', 'rüyada burun kanaması', 'rüyada elinde kan görmek', 'rüyada başkasının kanını görmek', 'kan rüya tabiri'],
    symbol: '🩸',
    sections: [
      { h: K, p: ['Kan, yaşam enerjisinin ve canlılığın sembolüdür. Rüyada kan görmek, enerjinin bir yerden “akıp gittiği” hissini, duygusal bir yarayı ya da çok yoğun bir duyguyu anlatabilir.', 'Rüya bir sağlık uyarısı değildir; ama bedeninle ilgili bir kaygın varsa bunu bir hekimle konuşmak her zaman iyidir.'] },
      { h: 'Psikolojik bakış', p: ['Jung’cu bakışta kan, hem yaşamı hem de fedakârlığı simgeler. Kanamak, sana çok şey kaybettiren bir ilişki ya da iş gibi enerji tüketen bir durumu gösterebilir.'] },
      { h: S, ul: ['Kendi kanamanı durduramamak: Enerjini ya da zamanını tüketen bir durumu sınırlayamamak.', 'Ellerde kan: Suçluluk ya da bir şeyden sorumlu tutulma hissi.', 'Başkasının kanını görmek: Birinin acısına tanık olma ya da onun için endişe.', 'Burun kanaması: Ani bir stres boşalması ya da kontrolsüz kalmış bir duygu.', 'Kanın durması: İyileşme ve toparlanma süreci.'] },
      { h: Q, ul: ['Hayatımda enerjimi en çok ne tüketiyor?', 'İyileşmesi gereken bir duygusal yaram var mı?'] },
    ],
    related: ['ruyada-olum-gormek', 'ruyada-yangin-gormek', 'ruyada-aglamak'],
  },
  {
    slug: 'ruyada-ciplak-olmak',
    title: 'Rüyada Çıplak Olmak Ne Anlama Gelir? Utanç ve Kırılganlık',
    description: 'Rüyada herkesin önünde çıplak kalmak en yaygın kaygı rüyalarındandır. Açığa çıkma korkusu, kırılganlık ve özgünlükle ilişkisi.',
    keywords: ['rüyada çıplak olmak', 'rüyada çıplak kalmak', 'rüyada insanların önünde çıplak olmak', 'rüyada çıplak gezmek', 'rüyada kıyafetini bulamamak', 'çıplaklık rüyası ne demek'],
    symbol: '🫣',
    sections: [
      { h: K, p: ['Çıplaklık rüyası çoğu zaman “açığa çıkma” korkusunu anlatır: hazırlıksız yakalanmak, bir eksikliğinin görülmesi ya da yargılanmak.', 'İlginç olan, bu rüyalarda çoğu zaman kimsenin çıplaklığı fark etmemesidir; utanç çoğunlukla bizim içimizdedir.'] },
      { h: 'Freud ve Jung’a göre', p: ['Freud bu rüyaları, utancın henüz olmadığı çocukluğa dönüş isteğiyle ilişkilendirir. Jung’cu bakışta ise çıplaklık, personanın (sosyal maskenin) düşmesi ve gerçek benliğin görünür olmasıdır; korkutucu olduğu kadar özgürleştirici de olabilir.'] },
      { h: S, ul: ['Herkesin önünde çıplak kalıp utanmak: Yeni bir rolde yetersiz görünme kaygısı.', 'Çıplak olup kimsenin fark etmemesi: Korktuğun kadar dikkat çekmediğine dair bir hatırlatma.', 'Çıplak olup rahat hissetmek: Kendini olduğun gibi kabul etme.', 'Kıyafet arayıp bulamamak: Kendini koruma yollarını kaybettiğin hissi.'] },
      { h: Q, ul: ['Şu an nerede “fazla görünür” hissediyorum?', 'Saklamaya çalıştığım bir yanım var mı?'] },
    ],
    related: ['ruyada-sinava-girmek', 'ruyada-dis-dokulmesi', 'ruyada-sac-kesmek'],
  },
  {
    slug: 'ruyada-aglamak',
    title: 'Rüyada Ağlamak Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada hıçkırarak ağlamak, birinin ağladığını görmek ya da ağlayarak uyanmak; bastırılmış duygular ve rahatlama ihtiyacıyla ilişkilidir.',
    keywords: ['rüyada ağlamak', 'rüyada hıçkırarak ağlamak', 'rüyada birinin ağladığını görmek', 'ağlayarak uyanmak', 'rüyada sevinçten ağlamak', 'ağlama rüyası ne demek'],
    symbol: '😢',
    sections: [
      { h: K, p: ['Rüyada ağlamak, çoğu zaman gün içinde ifade edemediğin duyguların uyku sırasında boşalmasıdır. Bu yüzden ağlama rüyalarından sonra sık sık hafiflemiş uyanılır.', 'Rüya üzücü olsa da çoğunlukla sağlıklı bir duygusal işleme işaretidir.'] },
      { h: 'Psikolojik bakış', p: ['Rüyalar, uyanıkken bastırdığımız duyguların güvenle yaşandığı bir alan sunar. Jung’cu bakışta gözyaşı, arınma ve kabullenmenin sembolüdür; sudan doğan yeni bir başlangıç gibi.'] },
      { h: S, ul: ['Hıçkırarak ağlamak: Uzun süredir taşıdığın bir yükün boşalması.', 'Ağlayamamak: Duyguları ifade etmede zorlanmak.', 'Başkasının ağladığını görmek: Onun ya da kendi bastırılmış hüznüne dair bir yansıma.', 'Sevinçten ağlamak: Rahatlama, umut ya da bir şeyin nihayet çözülmesi.', 'Ağlayarak uyanmak: Duygunun rüyada kalamayacak kadar güçlü olduğu.'] },
      { h: Q, ul: ['Son zamanlarda kendime ağlamaya izin vermediğim bir şey oldu mu?', 'Kimin önünde güçlü görünmek zorunda hissediyorum?'] },
    ],
    related: ['ruyada-olmus-birini-gormek', 'ruyada-su-gormek', 'ruyada-eski-sevgiliyi-gormek'],
  },
  {
    slug: 'ruyada-kaybolmak',
    title: 'Rüyada Kaybolmak ve Yolu Bulamamak Ne Anlama Gelir?',
    description: 'Rüyada tanımadığın bir yerde kaybolmak, evinin yolunu bulamamak ya da labirentte dolaşmak; yön, kimlik ve karar belirsizliğiyle ilişkilidir.',
    keywords: ['rüyada kaybolmak', 'rüyada yolu bulamamak', 'rüyada evin yolunu bulamamak', 'rüyada labirent görmek', 'rüyada şehirde kaybolmak', 'kaybolma rüyası ne demek'],
    symbol: '🧭',
    sections: [
      { h: K, p: ['Kaybolma rüyaları, hayatında yön duygusunun bulanıklaştığı dönemlerde sık görülür: iş değişikliği, taşınma, ilişki sonu ya da “ben ne istiyorum?” sorusu.', 'Rüyada aradığın yer, aslında neye ulaşmak istediğine dair önemli bir ipucudur.'] },
      { h: 'Jung’cu bakış', p: ['Jung, labirent ve kaybolma imgelerini bireyleşme yolculuğunun bir parçası olarak görür: Bazen eski haritalar işe yaramaz ve kendi yolunu bulmak için kaybolmak gerekir.'] },
      { h: S, ul: ['Evin yolunu bulamamak: Güvende ve ait hissettiğin yere dönme özlemi.', 'Bilmediğin bir şehirde kaybolmak: Yeni bir durumda yönsüz hissetmek.', 'Telefonun çekmemesi ya da harita açılmaması: Rehberliğe, desteğe ulaşamama hissi.', 'Labirentte dolaşmak: Bir problemin etrafında dönüp durmak.', 'Sonunda yolu bulmak: Belirsizliğin ardından gelen netlik.'] },
      { h: Q, ul: ['Şu an hayatımda nereye “dönmek” istiyorum?', 'Kimin haritasıyla yürüyorum: kendiminkiyle mi, başkalarınınkiyle mi?'] },
    ],
    related: ['ruyada-araba-kullanmak', 'ruyada-telefon-kaybetmek', 'ruyada-kovalanmak'],
  },
  {
    slug: 'ruyada-deniz-gormek',
    title: 'Rüyada Deniz Görmek Ne Anlama Gelir? Jung’a Göre Yorumu',
    description: 'Rüyada sakin ya da dalgalı deniz görmek, denizde yüzmek veya boğulmak; bilinçdışı, duygular ve sınırsızlıkla ilişkilidir.',
    keywords: ['rüyada deniz görmek', 'rüyada denizde yüzmek', 'rüyada dalgalı deniz görmek', 'rüyada sakin deniz görmek', 'rüyada denizde boğulmak', 'deniz rüya tabiri'],
    symbol: '🌊',
    sections: [
      { h: K, p: ['Deniz, Jung’cu rüya yorumunda bilinçdışının en güçlü sembollerinden biridir: derin, uçsuz bucaksız ve içinde ne olduğu tam bilinmeyen.', 'Denizin hali, çoğu zaman o dönemki duygusal halini yansıtır: sakin deniz iç huzuru, dalgalı deniz duygusal çalkantıyı.'] },
      { h: 'Jung’a göre deniz', p: ['Jung denizi kolektif bilinçdışının imgesi olarak görür; bütün yaşamın çıktığı ve geri döndüğü yer. Denize girmek, kendi derinliklerine inmeye hazırlık olarak okunabilir.'] },
      { h: S, ul: ['Sakin denizde yüzmek: Duygularınla barışık olmak.', 'Dev dalgalar: Kontrol edilemeyen bir duygunun ya da olayın yaklaşması.', 'Denizde boğulmak: Duygular ya da sorumluluklar altında kalma hissi.', 'Kıyıdan denizi izlemek: Derin bir konuya henüz girmeden bakmak.', 'Denizin dibine dalmak: Kendini daha derinden tanıma isteği.'] },
      { h: Q, ul: ['Bu aralar duygularım daha çok sakin mi, dalgalı mı?', 'Yüzleşmekten çekindiğim derin bir konu var mı?'] },
    ],
    related: ['ruyada-su-gormek', 'ruyada-balik-gormek', 'jung-arketipleri-rehberi'],
  },
  {
    slug: 'ruyada-balik-gormek',
    title: 'Rüyada Balık Görmek Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada balık tutmak, canlı ya da ölü balık görmek; bilinçdışından yükselen fikirler, sezgiler ve bereketle ilişkilendirilir.',
    keywords: ['rüyada balık görmek', 'rüyada balık tutmak', 'rüyada ölü balık görmek', 'rüyada canlı balık görmek', 'rüyada akvaryum görmek', 'balık rüya tabiri'],
    symbol: '🐟',
    sections: [
      { h: K, p: ['Balık, sudan, yani bilinçdışından yüzeye çıkan içerikleri temsil eder: yeni bir fikir, bir sezgi ya da fark etmeye başladığın bir duygu.', 'Halk tabirlerinde balık sık sık bereket ve hamilelikle ilişkilendirilir; psikolojik bakışta ise “yakalanmayı bekleyen bir içgörü” daha yararlı bir okumadır.'] },
      { h: 'Jung’cu bakış', p: ['Jung balığı, bilinçdışının derinliklerinde yaşayan canlı içeriklerin sembolü olarak görür. Balık tutmak, bu içeriklerle bağ kurma ve onları bilince taşıma çabasıdır.'] },
      { h: S, ul: ['Balık tutmak: Aradığın bir cevaba ya da fırsata yaklaşmak.', 'Elinden kayan balık: Tam yakalamak üzere olduğun bir fikri kaçırma hissi.', 'Ölü balık: Canlılığını yitirmiş bir umut, ilişki ya da proje.', 'Akvaryumdaki balıklar: Duygularını sınırlı ve güvenli bir alanda tutmak.', 'Çok sayıda balık: Bolluk, yaratıcılık ve fırsat hissi.'] },
      { h: Q, ul: ['Son zamanlarda aklıma gelip bir türlü yakalayamadığım fikir ne?', 'Hangi sezgimi ciddiye almıyorum?'] },
    ],
    related: ['ruyada-deniz-gormek', 'ruyada-su-gormek', 'ruyada-hamile-olmak'],
  },
  {
    slug: 'ruyada-orumcek-gormek',
    title: 'Rüyada Örümcek Görmek Ne Anlama Gelir? Jung’a Göre Yorumu',
    description: 'Rüyada örümcek ya da örümcek ağı görmek; kontrol, tuzağa düşme hissi, yaratıcılık ve anne figürüyle ilişkilendirilir.',
    keywords: ['rüyada örümcek görmek', 'rüyada siyah örümcek görmek', 'rüyada örümcek ağı görmek', 'rüyada örümcek ısırması', 'rüyada büyük örümcek görmek', 'örümcek rüya tabiri'],
    symbol: '🕷️',
    sections: [
      { h: K, p: ['Örümcek, ördüğü ağ nedeniyle hem yaratıcılığı hem de tuzağa düşürülme hissini simgeler. Rüyada örümcek, seni sıkıştıran bir ilişki, iş ya da düşünce örüntüsüne işaret edebilir.', 'Örümceğe karşı hissettiğin şey, tiksinti mi merak mı, yorumu önemli ölçüde değiştirir.'] },
      { h: 'Jung’cu bakış', p: ['Jung’cu yorumda örümcek bazen “yutan anne” imgesine, yani aşırı koruyucu ve kontrol edici bir figüre bağlanır. Öte yandan ağ örmek, kendi kaderini sabırla örmenin de sembolüdür.'] },
      { h: S, ul: ['Örümcek ağına takılmak: Çıkamadığın bir durum ya da ilişki.', 'Örümcek tarafından ısırılmak: Birinin sözlerinden ya da davranışından incinme.', 'Dev bir örümcek: Abartılmış ama yüzleşilebilir bir korku.', 'Örümceği öldürmek: Bir kontrolden kurtulma çabası.', 'Ağ ören örümceği izlemek: Sabır ve yaratıcı bir sürece hayranlık.'] },
      { h: Q, ul: ['Hayatımda kendimi “ağa takılmış” hissettiğim yer neresi?', 'Beni kontrol etmeye çalışan biri var mı, yoksa kontrol eden ben miyim?'] },
    ],
    related: ['ruyada-yilan-gormek', 'ruyada-anne-gormek', 'ruyada-kovalanmak'],
  },
  {
    slug: 'ruyada-at-gormek',
    title: 'Rüyada At Görmek Ne Anlama Gelir? Jung’a Göre Yorumu',
    description: 'Rüyada beyaz ya da siyah at görmek, ata binmek veya attan düşmek; içgüdüsel güç, özgürlük ve yaşam enerjisiyle ilişkilidir.',
    keywords: ['rüyada at görmek', 'rüyada beyaz at görmek', 'rüyada siyah at görmek', 'rüyada ata binmek', 'rüyada attan düşmek', 'at rüya tabiri'],
    symbol: '🐎',
    sections: [
      { h: K, p: ['At, insanın içgüdüsel gücünü ve yaşam enerjisini temsil eder. Ata binmek bu güçle uyum içinde olmayı; attan düşmek ise kontrolü kaybetme kaygısını anlatabilir.', 'Atın rengi, hızı ve sana karşı davranışı yorumun en önemli ipuçlarıdır.'] },
      { h: 'Jung’cu bakış', p: ['Jung atı, bilinçli zihnin taşıdığı ama tamamen kontrol edemediği hayvansal, içgüdüsel tarafın sembolü olarak görür. Binici ile at arasındaki ilişki, egonun içgüdülerle ilişkisini yansıtır.'] },
      { h: S, ul: ['Beyaz at: Saflık, umut ve yeni bir başlangıç enerjisi.', 'Siyah at: Güçlü ama henüz tanımadığın, gölgedeki bir enerji.', 'Dörtnala koşan at: Özgürlük isteği ya da hızla ilerleyen bir süreç.', 'Attan düşmek: Hırsının ya da tempo’nun seni aşması.', 'Yaralı at: Yorgun düşmüş bir yaşam enerjisi; dinlenme ihtiyacı.'] },
      { h: Q, ul: ['Enerjimi yönetebiliyor muyum, yoksa enerjim mi beni yönetiyor?', 'Hayatımda daha fazla özgürlüğe ihtiyaç duyduğum alan hangisi?'] },
    ],
    related: ['ruyada-araba-kullanmak', 'ruyada-kopek-gormek', 'jung-arketipleri-rehberi'],
  },
  {
    slug: 'ruyada-kus-gormek',
    title: 'Rüyada Kuş Görmek Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada uçan kuş, kafeste kuş ya da ölü kuş görmek; özgürlük, ruh, düşünceler ve haberlerle ilişkilendirilir.',
    keywords: ['rüyada kuş görmek', 'rüyada kafeste kuş görmek', 'rüyada ölü kuş görmek', 'rüyada kuşun eve girmesi', 'rüyada güvercin görmek', 'kuş rüya tabiri'],
    symbol: '🐦',
    sections: [
      { h: K, p: ['Kuşlar gökyüzüyle yer arasında gidip geldiği için düşünceleri, umutları, ruhu ve özgürlüğü temsil eder.', 'Kuşun özgür mü yoksa kafeste mi olduğu, kendi özgürlük hissine dair ne söylediğini gösterir.'] },
      { h: 'Jung’cu bakış', p: ['Jung kuşları ruhun ve sezgisel düşüncenin sembolü olarak görür; mitlerde tanrıların habercisi olmaları da bundandır. Rüyada kuş, bilinçdışından gelen bir mesajı taşıyabilir.'] },
      { h: S, ul: ['Gökyüzünde süzülen kuş: Özgürlük, bakış açısının genişlemesi.', 'Kafesteki kuş: Kendini sınırlanmış ya da ifade edemiyor hissetmek.', 'Kuşun eve girmesi: Hayatına giren yeni bir fikir ya da haber.', 'Ölü ya da yaralı kuş: Kırılmış bir umut ya da bastırılmış bir istek.', 'Kuş sürüsü: Toplulukla birlikte hareket etme ya da dağınık düşünceler.'] },
      { h: Q, ul: ['Kendimi hangi “kafeste” hissediyorum?', 'Son zamanlarda bana gelen hangi fikri dinlemedim?'] },
    ],
    related: ['ruyada-ucmak', 'ruyada-ucak-gormek', 'ruyada-kedi-gormek'],
  },
  {
    slug: 'ruyada-aldatilmak',
    title: 'Rüyada Aldatılmak Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada sevgilinin ya da eşinin seni aldatması çok yaygın bir rüyadır. Güvensizlik, ihmal edilme hissi ve kendine olan güvenle ilişkisi.',
    keywords: ['rüyada aldatılmak', 'rüyada sevgilinin aldatması', 'rüyada eşinin aldatması', 'rüyada aldatmak', 'rüyada ihanete uğramak', 'aldatılma rüyası ne demek'],
    symbol: '💔',
    sections: [
      { h: K, p: ['Aldatılma rüyası çoğu zaman gerçek bir aldatmanın işareti değildir. Daha sık olarak ilişkide ihmal edilme, ikinci planda kalma ya da yeterince değerli olmama kaygısını yansıtır.', 'Rüya, partnerinden çok kendi iç güvenlik hissin hakkında bilgi verir.'] },
      { h: 'Psikolojik bakış', p: ['Freud bu tür rüyalarda bastırılmış kıskançlık ve kaybetme korkusunu görür. Jung’cu bakışta “aldatan” kişi, senin kendi yanını, örneğin kendine ihanet ettiğin bir değerini de temsil edebilir.'] },
      { h: S, ul: ['Sevgilinin seni aldatması: İlişkide yeterince görülmeme kaygısı.', 'Tanıdığın biriyle aldatılmak: O kişiye karşı kıyas ya da yetersizlik duygusu.', 'Senin aldatman: Bir sınırı aşma isteği ya da ilişkide eksik kalan bir ihtiyaç.', 'Aldatmayı yakalamak: Görmezden geldiğin bir sorunu fark etmek.', 'Arkadaşın ihaneti: Güven ve aidiyet kaygısı.'] },
      { h: Q, ul: ['İlişkimde dile getirmediğim bir ihtiyacım var mı?', 'Kendi değerlerime sadık mıyım?'] },
    ],
    related: ['ruyada-eski-sevgiliyi-gormek', 'ruyada-dugun-gormek', 'ruyada-aglamak'],
  },
  {
    slug: 'ruyada-ucak-gormek',
    title: 'Rüyada Uçak Görmek ve Uçak Düşmesi Ne Anlama Gelir?',
    description: 'Rüyada uçağa binmek, uçağı kaçırmak ya da uçak düşmesi; büyük hedefler, geçişler ve kontrol kaygısıyla ilişkilidir.',
    keywords: ['rüyada uçak görmek', 'rüyada uçak düşmesi', 'rüyada uçağa binmek', 'rüyada uçağı kaçırmak', 'rüyada havalimanı görmek', 'uçak rüya tabiri'],
    symbol: '✈️',
    sections: [
      { h: K, p: ['Uçak rüyaları çoğu zaman büyük hedefleri, hızlı değişimleri ve bir yerden başka bir yere geçişi anlatır. Uçağın düşmesi ise bu hedeflerle ilgili başarısızlık ya da kontrol kaybı kaygısını yansıtır.', 'Uçuş korkusu olan kişilerde bu rüya, gerçek kaygının bir yansıması da olabilir; bir kehanet değildir.'] },
      { h: 'Psikolojik bakış', p: ['Uçak, kendin sürmediğin bir araçtır: Yolculuğun kontrolü başkasındadır. Bu yüzden uçak rüyaları, hayatındaki kararları başkalarına ne kadar bıraktığını da gösterebilir.'] },
      { h: S, ul: ['Uçağı kaçırmak: Bir fırsatı kaçırma ya da hazırlıksız kalma kaygısı.', 'Uçak düşmesi: Yüksek beklentilerin çökeceği korkusu.', 'Türbülans: Geçiş dönemindeki belirsizlik ve gerginlik.', 'Sorunsuz iniş: Zor bir sürecin güvenle tamamlanması.', 'Havalimanında beklemek: Bir kararın ya da değişimin eşiğinde olmak.'] },
      { h: Q, ul: ['Şu an hangi büyük hedefe doğru “havalanıyorum”?', 'Bu yolculuğun kontrolü kimde?'] },
    ],
    related: ['ruyada-ucmak', 'ruyada-dusmek', 'ruyada-araba-kullanmak'],
  },
  {
    slug: 'ruyada-anne-gormek',
    title: 'Rüyada Anneni Görmek Ne Anlama Gelir? Jung’a Göre Yorumu',
    description: 'Rüyada anneyi görmek, onunla tartışmak ya da annenin hastalanması; bakım, güven ve Jung’un anne arketipiyle ilişkilidir.',
    keywords: ['rüyada anneni görmek', 'rüyada anneyle tartışmak', 'rüyada annenin ağlaması', 'rüyada annenin hasta olması', 'rüyada anneye sarılmak', 'anne rüya tabiri'],
    symbol: '👩',
    sections: [
      { h: K, p: ['Anne rüyaları, gerçek annenle ilişkini olduğu kadar senin bakım, güven ve şefkat ihtiyacını da anlatır. Zor dönemlerde anne figürü sıkça rüyalara girer.', 'Rüyadaki annenin davranışı, kendine nasıl davrandığına dair de bir ayna olabilir.'] },
      { h: 'Jung’da anne arketipi', p: ['Jung’a göre anne arketipi hem besleyen, koruyan hem de bazen boğan, bırakmayan iki yüzlü bir figürdür. Rüyadaki anne, gerçek annenden çok bu evrensel imgeyi taşıyabilir.'] },
      { h: S, ul: ['Anneye sarılmak: Şefkat ve destek ihtiyacı.', 'Annenle tartışmak: Bağımsızlık ile bağlılık arasındaki gerilim.', 'Annenin hastalanması: Güvenlik kaynağını kaybetme kaygısı; bir sağlık kehaneti değildir.', 'Annenin seni eleştirmesi: İçselleştirdiğin eleştirel ses.', 'Ölmüş anneni görmek: Özlem ve yas süreci.'] },
      { h: Q, ul: ['Şu an kendime şefkatli davranabiliyor muyum?', 'Annemden bende kalan hangi ses beni yönlendiriyor?'] },
    ],
    related: ['ruyada-baba-gormek', 'ruyada-olmus-birini-gormek', 'jung-arketipleri-rehberi'],
  },
  {
    slug: 'ruyada-baba-gormek',
    title: 'Rüyada Babanı Görmek Ne Anlama Gelir? Psikolojik Yorumu',
    description: 'Rüyada babayı görmek, onunla konuşmak ya da babanın kızması; otorite, onay ihtiyacı ve kendi iç rehberinle ilişkilidir.',
    keywords: ['rüyada babanı görmek', 'rüyada babayla tartışmak', 'rüyada babanın kızması', 'rüyada ölmüş babayı görmek', 'rüyada babaya sarılmak', 'baba rüya tabiri'],
    symbol: '👨',
    sections: [
      { h: K, p: ['Baba figürü rüyalarda çoğunlukla otoriteyi, kuralları, korumayı ve onay ihtiyacını temsil eder. İş, kariyer ya da önemli kararlar döneminde sık görülür.', 'Gerçek babanla ilişkin kadar, kendi içindeki “yönlendiren ses”le ilişkini de anlatır.'] },
      { h: 'Freud ve Jung’a göre', p: ['Freud baba figürünü vicdan ve otorite ile ilişkilendirir. Jung’cu bakışta baba arketipi düzeni, anlamı ve dünyaya açılmayı temsil eder; rüyada baba ile ilişki, kendi otoriteni nasıl kullandığını gösterebilir.'] },
      { h: S, ul: ['Babanın sana kızması: Bir kuralı çiğneme ya da beklentiyi karşılayamama kaygısı.', 'Babanın seni övmesi: Onay ve takdir ihtiyacı.', 'Babanla tartışmak: Kendi yolunu çizme isteği.', 'Babanın zayıf ya da hasta görünmesi: Otoritenin ya da güvenlik hissinin sarsılması.', 'Ölmüş babanı görmek: Özlem, rehberlik isteği ve yas.'] },
      { h: Q, ul: ['Kimin onayını almadan karar veremiyorum?', 'Kendi hayatımın otoritesi olmaya hazır mıyım?'] },
    ],
    related: ['ruyada-anne-gormek', 'ruyada-olmus-birini-gormek', 'ruyada-sinava-girmek'],
  },
  {
    slug: 'ruyada-ayakkabi-gormek',
    title: 'Rüyada Ayakkabı Görmek ve Ayakkabı Kaybetmek Ne Anlama Gelir?',
    description: 'Rüyada yeni ayakkabı almak, ayakkabını kaybetmek ya da yırtık ayakkabı giymek; hayattaki yolun, rolün ve hazır olma hissiyle ilişkilidir.',
    keywords: ['rüyada ayakkabı görmek', 'rüyada ayakkabı kaybetmek', 'rüyada yeni ayakkabı almak', 'rüyada yırtık ayakkabı', 'rüyada çıplak ayakla yürümek', 'ayakkabı rüya tabiri'],
    symbol: '👟',
    sections: [
      { h: K, p: ['Ayakkabı, hayatta nasıl yürüdüğünü, hangi rolü üstlendiğini ve yola ne kadar hazır olduğunu simgeler.', 'Ayakkabını kaybetmek ya da yanlış ayakkabı giymek, bir rolde kendini rahat hissetmediğine işaret edebilir.'] },
      { h: 'Psikolojik bakış', p: ['“Birinin ayakkabısına girmek” deyimi gibi, rüyadaki ayakkabı da üstlendiğimiz kimlikle ilgilidir. Jung’cu bakışta yeni ayakkabı, yeni bir yaşam yoluna adım atmaya hazırlığı gösterebilir.'] },
      { h: S, ul: ['Yeni ayakkabı almak: Yeni bir başlangıç, rol ya da yol.', 'Ayakkabını kaybetmek: Kimliğinin ya da yönünün belirsizleşmesi.', 'Dar ya da acıtan ayakkabı: Sana uymayan bir rolü taşımak.', 'Çıplak ayakla yürümek: Savunmasızlık ama aynı zamanda doğallık.', 'Başkasının ayakkabısını giymek: Onun gibi olmaya çalışmak ya da empati.'] },
      { h: Q, ul: ['Şu an taşıdığım rollerden hangisi bana dar geliyor?', 'Yeni bir yola çıkmaya hazır mıyım?'] },
    ],
    related: ['ruyada-kaybolmak', 'ruyada-ciplak-olmak', 'ruyada-telefon-kaybetmek'],
  },
  {
    slug: 'ruyada-telefon-kaybetmek',
    title: 'Rüyada Telefon Kaybetmek ve Telefonun Bozulması Ne Anlama Gelir?',
    description: 'Rüyada telefonunu kaybetmek, ekranın kırılması ya da kimseyi arayamamak; bağlantı kopukluğu, iletişim kaygısı ve kontrol hissiyle ilişkilidir.',
    keywords: ['rüyada telefon kaybetmek', 'rüyada telefonun kırılması', 'rüyada kimseyi arayamamak', 'rüyada telefon çalınması', 'rüyada yeni telefon almak', 'telefon rüya tabiri'],
    symbol: '📱',
    sections: [
      { h: K, p: ['Telefon, modern rüyalarda iletişimin, bağlantının ve kontrolün sembolü haline geldi. Telefonu kaybetmek ya da arama yapamamak, birine ulaşamama ya da anlaşılmama kaygısını anlatır.', 'Gün içinde telefonla geçen yoğun zaman da bu rüyaları besler; her zaman derin bir anlamı olmayabilir.'] },
      { h: 'Psikolojik bakış', p: ['Rüyada telefonun çalışmaması, ihtiyaç duyduğunda yardım isteyememe hissinin yaygın bir modern versiyonudur. Telefon aynı zamanda kimliğin ve sosyal ağın bir uzantısıdır; onu kaybetmek “kim olduğumu kaybediyorum” hissine dokunabilir.'] },
      { h: S, ul: ['Telefonu kaybetmek: Bağlantı ya da kontrol kaybı kaygısı.', 'Numarayı tuşlayamamak: Birine bir şey söylemek isteyip söyleyememek.', 'Ekranın kırılması: İletişimde bir kırılma ya da gerginlik.', 'Telefonun çalınması: Mahremiyetinin ihlal edildiği hissi.', 'Telefonsuz rahat hissetmek: Sürekli ulaşılabilir olmaktan uzaklaşma isteği.'] },
      { h: Q, ul: ['Ulaşmak isteyip ulaşamadığım biri var mı?', 'Sürekli bağlı olmak beni yoruyor mu?'] },
    ],
    related: ['ruyada-kaybolmak', 'ruyada-para-gormek', 'ruyada-sinava-girmek'],
  },
]
